# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2025 Lee Cannon <leecannon@leecannon.xyz>

version = 1
SPDX-PackageName = "zig-bitjuggle"
SPDX-PackageSupplier = "Lee Cannon <leecannon@leecannon.xyz>"
SPDX-PackageDownloadLocation = "https://github.com/leecannon/zig-bitjuggle"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "2025 Lee Cannon <leecannon@leecannon.xyz>"
